---
- name: Set broker_sg_rules
  set_fact:
    broker_sg_rules: []

- name: Add each sg rule to broker_sg_rules
  set_fact:
    broker_sg_rules: "{{broker_sg_rules}} + [{'cidr_ip':'{{item.cidr_block}}','to_port':'{{activemq_broker_port}}','from_port':'{{activemq_broker_port}}','proto':'tcp'}]"
  with_items: "{{ec2_subnet_info}}"
  loop_control:
    label: "{{item.id}}: {{item.cidr_block}}"
  when: ec2_subnet_info is defined

- include: ../../ec2_launcher/tasks/update_sg.yml   # update EC2 sg rules
  vars:
    - sg_info: "{{ec2_sg_info}}"
    - my_sg_rules: "{{ec2_sg_rules|unique}}"
    - my_extra_sg_rules: "{{broker_sg_rules}} + {{activemq_sg_rules}} + {{activemq_extra_sg_rules}}"
  when: ec2_sg_info is defined and activemq_broker_ip != '127.0.0.1' and (ec2_sg_rules|length > 0 or broker_sg_rules|length > 0 or activemq_sg_rules|length > 0 or activemq_extra_sg_rules|length > 0)

- name: Create group account for activemq
  group:
    name: "{{activemq_group}}"
    state: present

- name: Create user account for activemq
  user:
    name: "{{activemq_user}}"
    comment: ActiveMQ
    group: "{{activemq_group}}"
    state: present
    shell: /sbin/nologin
    createhome: no

- name: Modify limits.conf on nofile
  pam_limits:
    domain: "{{activemq_user}}"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{activemq_nofile_limit}}"
  with_items:
   - hard
   - soft      

- name: Modify limits.conf on stack
  pam_limits:
    domain: "{{activemq_user}}"
    limit_type: "{{ item }}"
    limit_item: stack
    value: "{{activemq_stack_limit}}"
  with_items:
    - hard
    - soft

- name: Create dirs of /opt and /var/cache/ansible
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /opt
    - /var/cache/ansible

- name: Get stats of amq tarball
  stat:
    path: "/var/cache/ansible/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    get_md5: no
    get_checksum: no
  register: st_amq_tarball

- name: Gets the tarball
  get_url:
    url: "{{activemq_repo_url}}/{{activemq_version}}/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /var/cache/ansible/
  when: not st_amq_tarball.stat.exists
  register: new_archive_amq

- name: Get stats of /opt/activemq
  stat:
    path: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    get_md5: no
    get_checksum: no
  register: st_activemq

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
  when: new_archive_amq is changed or not st_activemq.stat.exists

- name: Create symlink of /opt/activemq
  file:
    src: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    dest: /opt/activemq
    state: link

- name: Set my_list
  set_fact:
    remote_host: ''
    remote_uri: ''
    my_list: "['{{ansible_host}}']"

- name: Set remote_host
  set_fact:
    remote_host: "{{activemq_network_brokers|difference(my_list)|first}}"
  when: activemq_network_brokers|unique|length == 2

- name: Reset remote_host to private ip
  set_fact:
    remote_host: "{{ec2_private_ips[0] if remote_host == activemq_network_brokers[0] else ec2_private_ips[1]}}"
  when: ec2_private_ips is defined and ec2_private_ips|length == 2

- name: Set br_host to private ip
  set_fact:
    br_host: "ip-{{ec2_private_ips[0]|replace('.','-') if ansible_host == activemq_network_brokers[0] else ec2_private_ips[1]|replace('.','-')}}"
  when: ec2_private_ips is defined and ec2_private_ips|length == 2

- name: Set remote uri
  set_fact:
    remote_uri: "static:(tcp://{{remote_host}}:{{activemq_broker_port}})"
  when: activemq_network_brokers|unique|length == 2 and ansible_host in activemq_network_brokers and remote_host != 'localhost'

- name: Display remote host and uri
  debug:
    msg:
      - "remote_host: {{remote_host}}"
      - "network_connector_uri: {{remote_uri}}"
  when: remote_uri|length > 0

- name: Template of activemq.xml
  template:
    src: activemq.xml.j2
    dest: "/opt/activemq/conf/activemq.xml"
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
    mode: 0640
  vars:
    remote_host: "{{remote_host}}"
    remote_uri: "{{remote_uri}}"
    broker_host: "{{br_host|default(ansible_host)}}"
    broker_port: "{{activemq_broker_port}}"
    broker_ip: "{{activemq_broker_ip}}"
    broker_user: "{{activemq_broker_user}}"
    broker_passwd: "{{activemq_broker_passwd}}"
    ks_passwd: "{{activemq_ks_passwd}}"
    ssl_status: "{{activemq_ssl}}"
    jmx_status: "{{activemq_jmx_status}}"
    jmx_port: "{{activemq_jmx_port}}"
    percent_heap: "{{activemq_percent_heap}}"
    prefetch_size: "{{activemq_prefetch_size}}"
    pending_limit: "{{activemq_pending_limit}}"
    store_usage: "{{activemq_store_usage}}"
    temp_usage: "{{activemq_temp_usage}}"
  notify: Restart_activemq.service

- name: Template of env
  template:
    src: env.j2
    dest: /opt/activemq/bin/env
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
  vars:
    opts_memory: "{{activemq_opts_memory}}"
  notify: Restart_activemq.service

- name: Template of configs
  template:
    src: "{{item}}.j2"
    dest: "/opt/activemq/conf/{{item}}"
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
    mode: 0640
  with_items:
    - jetty.xml
    - jetty-realm.properties
    - jmx.access
    - jmx.password
    - users.properties
    - groups.properties
    - credentials.properties
  notify: Restart_activemq.service

- name: Copy secured config files
  copy:
    src: "{{item}}"
    dest: "/opt/activemq/conf/{{item}}"
    mode: 0640
  with_items:
    - broker.ks
  notify: Restart_activemq.service

- name: Copy config files
  copy:
    src: "{{item}}"
    dest: "/opt/activemq/conf/{{item}}"
    mode: 0644
  with_items:
    - broker.ts
    - java.security
    - log4j.properties
    - logging.properties
    - login.config
  notify: Restart_activemq.service

- name: Copy activemq.service
  copy:
    src: activemq.service
    dest: "{{activemq_systemd_dir}}/system/"
    mode: 0644
  notify: Restart_activemq.service

- name: Open broker port
  iptables:
    chain: INPUT
    destination_port: "{{activemq_broker_port}}"
    action: insert
    jump: ACCEPT
    match: state
    ctstate: NEW
    protocol: tcp
    state: present
  when: common_iptables != 'disabled' and activemq_broker_ip != '127.0.0.1'
  register: port_amq_result

- name: Open console port
  iptables:
    chain: INPUT
    destination_port: "{{activemq_admin_port}}"
    action: insert
    jump: ACCEPT
    match: state
    ctstate: NEW
    protocol: tcp
    state: present
  when: common_iptables != 'disabled' and activemq_admin_ip != '127.0.0.1'
  register: port_console_result

- name: Save iptables
  shell: "/sbin/iptables-save > /etc/sysconfig/iptables"
  when: port_amq_result is changed or port_console_result is changed

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of activemq.monit
  template:
    src: activemq.monit.j2
    dest: "{{monit_includedir}}/activemq.monit"
    mode: 0644
  vars:
    pidfile: "{{activemq_pidfile}}"
    start_program: '/usr/bin/systemctl start activemq'
    stop_program: '/usr/bin/systemctl stop activemq'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service

- name: Get stats of agent
  stat:
    path: "{{qbroker_dir}}/agent"
    get_md5: no
    get_checksum: no
  register: st_agent

- name: Template of json files for MonitorAgent
  template:
    src: "{{item}}.j2"
    dest: "{{qbroker_dir}}/agent/{{item}}"
    mode: 0644
  vars:
    stats_url: "{{MonitorAgent_stats_url}}"
    broker_name: "{{br_host|default(ansible_host)}}"
    admin_port: "{{MonitorAgent_admin_port}}"
    qb_dir: "{{qbroker_dir}}"
    log_dir: "{{qbroker_logdir}}"
  with_items: "{{activemq_json_files}}"
  when: st_agent.stat.exists and activemq_json_files|length > 0
  notify: Restart_MonitorAgent
