---
- include: update_sg.yml   # add the extra rules to the security group
  when: activemq_admin_ip != '127.0.0.1'

- name: Create group account for activemq
  group:
    name: "{{activemq_group}}"
    state: present

- name: Create user account for activemq
  user:
    name: "{{activemq_user}}"
    comment: ActiveMQ
    group: "{{activemq_group}}"
    state: present
    shell: /sbin/nologin
    createhome: no

- name: Create dirs of /opt and /var/cache/ansible
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /opt
    - /var/cache/ansible

- name: Get stats of amq tarball
  stat:
    path: "/var/cache/ansible/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    get_md5: no
    get_checksum: no
  register: st_amq_tarball

- name: Gets the tarball
  get_url:
    url: "{{activemq_repo_url}}/{{activemq_version}}/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /var/cache/ansible/
  when: not st_amq_tarball.stat.exists
  register: new_archive_amq

- name: Get stats of /opt/activemq
  stat:
    path: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    get_md5: no
    get_checksum: no
  register: st_activemq

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{activemq_pkg_name}}-{{activemq_version}}-bin.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
  when: new_archive_amq|changed or not st_activemq.stat.exists

- name: Create symlink of /opt/activemq
  file:
    src: "/opt/{{activemq_pkg_name}}-{{activemq_version}}"
    dest: /opt/activemq
    state: link

- name: Template of configs
  template:
    src: "{{item}}.j2"
    dest: "/opt/activemq/conf/{{item}}"
    owner: "{{activemq_user}}"
    group: "{{activemq_group}}"
    mode: 0644
  with_items:
    - activemq.xml
    - jetty.xml
    - users.properties
    - groups.properties
    - credentials.properties
  notify: Restart_activemq.service

- name: Copy activemq.service
  copy:
    src: activemq.service
    dest: "{{activemq_systemd_dir}}/system/"
    mode: 0644
  notify: Restart_activemq.service

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of activemq.monit
  template:
    src: activemq.monit.j2
    dest: "{{monit_includedir}}/activemq.monit"
    mode: 0644
  vars:
    pidfile: "{{activemq_pidfile}}"
    start_program: '/usr/bin/systemctl start activemq'
    stop_program: '/usr/bin/systemctl stop activemq'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
